---
- name: SELinux configuration
  selinux:
    policy: targeted
    state: permissive
  when: ansible_selinux.config_mode == 'enforcing'

- name: Disable ipv6
  sysctl:
    state: present
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

- name: Update packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Update epel-release repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes
